import 'package:youtube_explode_dart/youtube_explode_dart.dart';

void main() async {
  var yt = YoutubeExplode();
  String videoId = "V1bFr2SWP1I"; // Just an example, replace with a real one
  
  try {
    var manifest = await yt.videos.closedCaptions.getManifest(videoId);
    if (manifest.tracks.isNotEmpty) {
      print("Available tracks:");
      for (var track in manifest.tracks) {
        print(" - ${track.language.name} (${track.language.code}) - Auto: ${track.isAutoGenerated}");
      }
      
      var trackInfo = manifest.tracks.first;
      var closedCaptions = await yt.videos.closedCaptions.get(trackInfo);
      
      print("First 5 captions:");
      for (var i = 0; i < 5 && i < closedCaptions.captions.length; i++) {
        var cc = closedCaptions.captions[i];
        print("[${cc.offset}] ${cc.text}");
      }
    } else {
      print("No CC tracks found for video $videoId");
    }
  } catch (e) {
    print("Error: $e");
  } finally {
    yt.close();
  }
}
