import 'package:youtube_explode_dart/youtube_explode_dart.dart';

void main() async {
  final yt = YoutubeExplode();
  final videoId = 'kJQP7kiw5Fk'; 
  
  try {
    final manifest = await yt.videos.closedCaptions.getManifest(videoId);
    print('Manifest tracks: ${manifest.tracks.length}');
    
    ClosedCaptionTrackInfo? selectedTrack;

    // 1. Fokus utama: Cari track yang auto-generated dari YouTube (karena ini bahasa aslinya)
    selectedTrack = manifest.tracks.where((t) => t.isAutoGenerated).firstOrNull;

    // 2. Jika tidak ada auto-generated, cari subtitle manual berbahasa Indonesia
    if (selectedTrack == null) {
      selectedTrack = manifest.tracks.where((t) => t.language.code == 'id' || t.language.code.startsWith('id')).firstOrNull;
    }

    // 3. Fallback terakhir, ambil track pertama yang tersedia
    selectedTrack ??= manifest.tracks.first;

    print('✅ [YouTube CC] Selected track: ${selectedTrack.language.name} (auto: ${selectedTrack.isAutoGenerated})');
  } catch (e) {
    print('Error: $e');
  } finally {
    yt.close();
  }
}
