import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import '../models/lyric_line.dart';

class LyricsService {
  static final YoutubeExplode _yt = YoutubeExplode();

  /// Fetches synced lyrics from YouTube closed captions based on videoId.
  static Future<List<LyricLine>?> fetchLyrics(String videoId) async {
    try {
      final manifest = await _yt.videos.closedCaptions.getManifest(videoId);
      if (manifest.tracks.isEmpty) {
        print('❌ [YouTube CC] No closed captions found for $videoId');
        return null;
      }

      ClosedCaptionTrackInfo? selectedTrack;

      // 1. Fokus utama: Cari track yang auto-generated dari YouTube (karena ini bahasa aslinya)
      selectedTrack = manifest.tracks.where((t) => t.isAutoGenerated).firstOrNull;

      // 2. Jika tidak ada auto-generated, cari subtitle manual berbahasa Indonesia
      if (selectedTrack == null) {
        selectedTrack = manifest.tracks.where((t) => t.language.code == 'id' || t.language.code.startsWith('id')).firstOrNull;
      }

      // 3. Fallback terakhir, ambil track pertama yang tersedia
      selectedTrack ??= manifest.tracks.first;

      print('✅ [YouTube CC] Selected track: ${selectedTrack.language.name} (auto: ${selectedTrack.isAutoGenerated})');

      final closedCaptions = await _yt.videos.closedCaptions.get(selectedTrack);
      
      final List<LyricLine> lines = [];
      for (var caption in closedCaptions.captions) {
        // Hilangkan tag seperti [Music], [Applause], (Chorus), dan simbol nada ♪
        String text = caption.text.replaceAll(RegExp(r'\[.*?\]|\(.*?\)|♪'), '').trim();
        
        // Skip empty text or purely whitespace captions to keep lyrics clean
        if (text.isNotEmpty) {
          lines.add(LyricLine(
            time: caption.offset,
            text: text,
          ));
        }
      }

      // Ensure chronological order
      lines.sort((a, b) => a.time.compareTo(b.time));
      return lines;
    } catch (e) {
      print('Error fetching lyrics from YouTube: $e');
      return null;
    }
  }
}
